name: Deploy Portal pay for Betgambler Other client 5
on:
  push:
     branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
            fetch-depth: 0
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: |
              ssh-keygen -F github.com || ssh-keyscan github.com >> ~/.ssh/known_hosts
              cd /home
              if [ ! -d "github" ]; then
                echo "Creating Directory GitHub"
                mkdir -p github
              fi  
              cd github
              if [ ! -d "app-betgambler-frm6" ]; then
                mkdir -p app-betgambler-frm6
              fi
              cd app-betgambler-frm6
              rm -rf  frontregister_6
              git clone -b production git@github.com:granaber/frontregister_6.git
              cd frontregister_6
              docker compose up --build  --force-recreate  -d
              